.lanrzipUtilsComponents_js_metadata <- function() {
deps_metadata <- list(`lanrzip_utils_components` = structure(list(name = "lanrzip_utils_components",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-LanrzipUtilsComponents.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "lanrzipUtilsComponents",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`lanrzip_utils_components` = structure(list(name = "lanrzip_utils_components",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-LanrzipUtilsComponents.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "lanrzipUtilsComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`lanrzip_utils_components` = structure(list(name = "lanrzip_utils_components",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'lanrzip_utils_components.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "lanrzipUtilsComponents",
all_files = FALSE), class = "html_dependency"),
`lanrzip_utils_components` = structure(list(name = "lanrzip_utils_components",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'lanrzip_utils_components.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "lanrzipUtilsComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
